
import { Staff, Task, Reservation, AttendanceRecord } from '../types';

export const MOCK_STAFF: Staff[] = [
  {
    id: 'eh',
    name: 'Example Housekeeper',
    initials: 'EH',
    role: 'Housekeeper',
    avatarColor: 'bg-orange-400',
    totalHours: 8,
    workedHours: 0,
    isWorking: false,
    shiftStart: 9,
    shiftEnd: 17,
  },
  {
    id: 'ff',
    name: 'Frank Fu',
    initials: 'FF',
    role: 'Technician',
    avatarColor: 'bg-blue-500',
    totalHours: 8,
    workedHours: 4.5,
    isWorking: true,
    shiftStart: 9,
    shiftEnd: 17,
  },
  {
    id: 'th',
    name: 'Team Housekeeper',
    initials: 'TH',
    role: 'Housekeeper',
    avatarColor: 'bg-green-500',
    totalHours: 8,
    workedHours: 3,
    isWorking: true,
    shiftStart: 10,
    shiftEnd: 18,
  },
  {
    id: 'to',
    name: 'Test OP',
    initials: 'TO',
    role: 'Operator',
    avatarColor: 'bg-teal-600',
    totalHours: 8,
    workedHours: 1,
    isWorking: false,
    shiftStart: 9,
    shiftEnd: 17,
  },
  {
    id: 'js',
    name: 'John Smith',
    initials: 'JS',
    role: 'Maintenance',
    avatarColor: 'bg-purple-500',
    totalHours: 8,
    workedHours: 2,
    isWorking: true,
    shiftStart: 12,
    shiftEnd: 20,
  },
  {
    id: 'ad',
    name: 'Alice Doe',
    initials: 'AD',
    role: 'Inspector',
    avatarColor: 'bg-red-500',
    totalHours: 7,
    workedHours: 5,
    isWorking: false,
    shiftStart: 9,
    shiftEnd: 16,
  },
  {
    id: 'mk',
    name: 'Mike K.',
    initials: 'MK',
    role: 'Delivery',
    avatarColor: 'bg-indigo-500',
    totalHours: 6,
    workedHours: 1,
    isWorking: true,
    shiftStart: 9,
    shiftEnd: 15,
  },
  {
    id: 'sl',
    name: 'Sarah Lee',
    initials: 'SL',
    role: 'Housekeeper',
    avatarColor: 'bg-pink-500',
    totalHours: 8,
    workedHours: 6,
    isWorking: true,
    shiftStart: 10,
    shiftEnd: 18,
  },
  {
    id: 'br',
    name: 'Ben Ross',
    initials: 'BR',
    role: 'Technician',
    avatarColor: 'bg-cyan-600',
    totalHours: 9,
    workedHours: 3.5,
    isWorking: false,
    shiftStart: 11,
    shiftEnd: 20,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't1',
    staffId: 'ff',
    title: 'Fix lamp',
    location: '2607 Guest Room',
    type: 'maintenance',
    startTime: 11.25, // 11:15 AM Actual
    duration: 1.25,
    plannedStartTime: 11, // Planned 11:00
    plannedDuration: 1, // Planned 1h
    status: 'delayed',
    notes: '+15m late start',
  },
  {
    id: 't2',
    staffId: 'ff',
    title: 'Check HVAC',
    location: 'Beach House',
    type: 'inspection',
    startTime: 13, // 1:00 PM
    duration: 2,
    plannedStartTime: 13,
    plannedDuration: 2,
    status: 'pending',
  },
  {
    id: 't3',
    staffId: 'th',
    title: 'Deep cleaning',
    location: 'Ocean View Villa',
    type: 'cleaning',
    startTime: 10, // 10:00 AM
    duration: 4.5, // Running long
    plannedStartTime: 10,
    plannedDuration: 4, // Planned 4h
    status: 'in-progress',
    notes: 'Running overtime',
  },
  {
    id: 't4',
    staffId: 'unassigned',
    title: 'Towel Delivery',
    location: 'Pool Area',
    type: 'delivery',
    startTime: 9.5,
    duration: 0.5,
    plannedStartTime: 9.5,
    plannedDuration: 0.5,
    status: 'pending',
  },
  {
    id: 't5',
    staffId: 'js',
    title: 'Pool Filter',
    location: 'Main Pool',
    type: 'maintenance',
    startTime: 13,
    duration: 2,
    plannedStartTime: 13,
    plannedDuration: 2,
    status: 'completed',
  },
  {
    id: 't6',
    staffId: 'ad',
    title: 'Safety Check',
    location: 'Lobby',
    type: 'inspection',
    startTime: 14.5,
    duration: 1,
    plannedStartTime: 14.5,
    plannedDuration: 1,
    status: 'pending',
  },
  {
    id: 't7',
    staffId: 'unassigned',
    title: 'Room 204 Clean',
    location: 'Room 204',
    type: 'cleaning',
    startTime: 0,
    duration: 1,
    plannedStartTime: 0,
    plannedDuration: 1,
    status: 'pending',
  },
  {
    id: 't8',
    staffId: 'unassigned',
    title: 'Lobby Light',
    location: 'Lobby',
    type: 'maintenance',
    startTime: 0,
    duration: 0.5,
    plannedStartTime: 0,
    plannedDuration: 0.5,
    status: 'pending',
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'r1',
    propertyCode: '1820SD WIR',
    reservationCode: 'HA-zYkvtXP',
    startDate: '2025-12-20',
    endDate: '2025-12-27',
    source: 'VRBO',
    guestName: 'Catherine Henry',
    nights: 7,
    status: 'Confirmed',
    guestCount: 1,
    payout: 1250.00,
    email: 'catherine.henry@example.com',
    phone: '+1 (555) 123-4567'
  },
  {
    id: 'r2',
    propertyCode: '231BD BV',
    reservationCode: '',
    startDate: '2025-12-28',
    endDate: '2026-01-07',
    source: 'Airbnb',
    guestName: 'Victor',
    nights: 10,
    status: 'Confirmed',
    guestCount: 12,
    payout: 3400.50,
    email: 'victor@example.com'
  },
  {
    id: 'r3',
    propertyCode: '8817RS WAW',
    reservationCode: 'HMQN9PFC8Q',
    startDate: '2025-12-30',
    endDate: '2026-01-03',
    source: 'Airbnb',
    guestName: 'Jose Nava',
    nights: 4,
    status: 'Confirmed',
    guestCount: 10,
    payout: 890.00
  },
  {
    id: 'r4',
    propertyCode: '1244CD CG',
    reservationCode: 'HMKQPAPXPS',
    startDate: '2026-02-05',
    endDate: '2026-02-10',
    source: 'Airbnb',
    guestName: 'James Gauthier',
    nights: 5,
    status: 'Confirmed',
    guestCount: 5,
    payout: 1100.00
  },
  {
    id: 'r5',
    propertyCode: '1852NC WAW',
    reservationCode: '',
    startDate: '2025-12-28',
    endDate: '2026-01-02',
    source: 'Airbnb',
    guestName: 'Samantha',
    nights: 5,
    status: 'Confirmed',
    guestCount: 9,
    payout: 1550.00
  },
  {
    id: 'r6',
    propertyCode: '4185PD SL',
    reservationCode: '',
    startDate: '2026-02-24',
    endDate: '2026-03-05',
    source: 'Airbnb',
    guestName: 'Brent',
    nights: 9,
    status: 'Confirmed',
    guestCount: 8,
    payout: 2100.00
  },
  {
    id: 'r7',
    propertyCode: '3409LW WIR',
    reservationCode: 'HMAMQ3YAN4',
    startDate: '2026-01-22',
    endDate: '2026-01-25',
    source: 'Airbnb',
    guestName: 'Janiyah Brown',
    nights: 3,
    status: 'Confirmed',
    guestCount: 11,
    payout: 750.00
  },
  {
    id: 'r8',
    propertyCode: '2993PS SL',
    reservationCode: 'HMYA32SP2W',
    startDate: '2025-12-27',
    endDate: '2026-01-10',
    source: 'Airbnb',
    guestName: 'Bernardo R Vieira',
    nights: 14,
    status: 'Confirmed',
    guestCount: 9,
    payout: 4200.00
  },
  {
    id: 'r9',
    propertyCode: '1060LS CG',
    reservationCode: '',
    startDate: '2026-01-21',
    endDate: '2026-02-05',
    source: 'Airbnb',
    guestName: 'Brenda',
    nights: 15,
    status: 'Confirmed',
    guestCount: 4,
    payout: 3800.00
  },
  {
    id: 'r10',
    propertyCode: '2540HS WH (New)',
    reservationCode: 'HMB2M5X4W8',
    startDate: '2026-01-24',
    endDate: '2026-01-28',
    source: 'Airbnb',
    guestName: 'Gabrielle',
    nights: 4,
    status: 'Confirmed',
    guestCount: 9,
    payout: 1200.00
  },
   {
    id: 'r11',
    propertyCode: '1820SD WIR',
    reservationCode: '',
    startDate: '2025-12-29',
    endDate: '2026-01-02',
    source: 'Airbnb',
    guestName: 'Veronica',
    nights: 4,
    status: 'Confirmed',
    guestCount: 14,
    payout: 1450.00
  },
  {
    id: 'r12',
    propertyCode: '1820SD WIR',
    reservationCode: '',
    startDate: '2025-12-29',
    endDate: '2026-01-03',
    source: 'Airbnb',
    guestName: 'Annalisa',
    nights: 5,
    status: 'Confirmed',
    guestCount: 4,
    payout: 900.00
  },
  {
    id: 'r13',
    propertyCode: '2936PS SL',
    reservationCode: 'HMQ8X2D9EF',
    startDate: '2026-01-01',
    endDate: '2026-01-11',
    source: 'Airbnb',
    guestName: 'Cristian Leandro Mantelli',
    nights: 10,
    status: 'Confirmed',
    guestCount: 14,
    payout: 3100.00
  }
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'a1',
    userId: 'u1',
    user: {
      id: 'u1',
      fullName: 'Luis Manuel',
      avatarColor: 'bg-indigo-600',
      initials: 'LU',
      department: 'Orlando Operation Team',
      position: 'Maintenance'
    },
    attendanceDate: '2025-11-19',
    status: 'Working',
    firstClockInAt: '2025-11-19T16:47:00',
    finalClockOutAt: '2025-11-19T20:52:00',
    clockInCount: 3,
    clockOutCount: 3,
    totalWorkingDurationSec: 30480 // 8h 28m
  },
  {
    id: 'a2',
    userId: 'u2',
    user: {
      id: 'u2',
      fullName: 'Carolina',
      avatarColor: 'bg-orange-500',
      initials: 'CS',
      department: 'Orlando Operation Team',
      position: 'Cleaner'
    },
    attendanceDate: '2025-11-19',
    status: 'Shift End',
    firstClockInAt: '2025-11-19T15:42:00',
    finalClockOutAt: '2025-11-19T18:57:00',
    clockInCount: 3,
    clockOutCount: 3,
    totalWorkingDurationSec: 30600 // 8h 30m
  },
  {
    id: 'a3',
    userId: 'u3',
    user: {
      id: 'u3',
      fullName: 'Nestor Daniel',
      avatarColor: 'bg-teal-400',
      initials: 'NB',
      department: 'Orlando Operation Team',
      position: 'Maintenance'
    },
    attendanceDate: '2025-11-19',
    status: 'Working',
    firstClockInAt: '2025-11-19T09:51:00',
    finalClockOutAt: '2025-11-19T18:21:00',
    totalWorkingDurationSec: 30600
  },
  {
    id: 'a4',
    userId: 'u4',
    user: {
      id: 'u4',
      fullName: 'Diego',
      avatarColor: 'bg-slate-800',
      initials: 'D',
      department: 'Toronto Office',
      position: 'Inspector'
    },
    attendanceDate: '2025-11-19',
    status: 'In break',
    firstClockInAt: '2025-11-19T09:38:00',
    finalClockOutAt: '2025-11-19T14:26:00',
    totalWorkingDurationSec: 17280 // 4h 48m
  },
  {
    id: 'a5',
    userId: 'u5',
    user: {
      id: 'u5',
      fullName: 'Pito',
      avatarColor: 'bg-yellow-300',
      initials: 'PM',
      department: 'Orlando Operation Team',
      position: 'Cleaner'
    },
    attendanceDate: '2025-11-19',
    status: 'Working',
    firstClockInAt: '2025-11-19T09:32:00',
    finalClockOutAt: '2025-11-19T18:02:00',
    totalWorkingDurationSec: 30600
  },
  {
    id: 'a6',
    userId: 'u6',
    user: {
      id: 'u6',
      fullName: 'Fabricio',
      avatarColor: 'bg-green-600',
      initials: 'FP',
      department: 'Orlando Operation Team',
      position: 'Maintenance'
    },
    attendanceDate: '2025-11-19',
    status: 'Shift End',
    firstClockInAt: '2025-11-19T09:31:00',
    finalClockOutAt: '2025-11-19T18:01:00',
    totalWorkingDurationSec: 30600
  },
  {
    id: 'a7',
    userId: 'u7',
    user: {
      id: 'u7',
      fullName: 'Hugo',
      avatarColor: 'bg-slate-400',
      initials: 'HM',
      department: 'Orlando Operation Team',
      position: 'Maintenance'
    },
    attendanceDate: '2025-11-19',
    status: 'Working',
    firstClockInAt: '2025-11-19T09:20:00',
    finalClockOutAt: '2025-11-19T16:58:00',
    totalWorkingDurationSec: 27480
  },
  {
    id: 'a8',
    userId: 'u8',
    user: {
      id: 'u8',
      fullName: 'Sebastian',
      avatarColor: 'bg-slate-500',
      initials: 'S',
      department: 'Orlando Operation Team',
      position: 'Maintenance'
    },
    attendanceDate: '2025-11-19',
    status: 'Shift End',
    firstClockInAt: '2025-11-19T08:54:00',
    finalClockOutAt: '2025-11-19T17:13:00',
    totalWorkingDurationSec: 29940
  },
  {
    id: 'a9',
    userId: 'u9',
    user: {
      id: 'u9',
      fullName: 'Eric',
      avatarColor: 'bg-indigo-900',
      initials: 'E',
      department: 'Development Team',
      position: 'Office Admin'
    },
    attendanceDate: '2025-11-19',
    status: 'Off duty',
    totalWorkingDurationSec: 0
  },
  {
    id: 'a10',
    userId: 'u10',
    user: {
      id: 'u10',
      fullName: 'Madeline',
      avatarColor: 'bg-slate-700',
      initials: 'M',
      department: 'Offshore CS Team',
      position: 'Guest Service'
    },
    attendanceDate: '2025-11-19',
    status: 'Off duty',
    totalWorkingDurationSec: 0
  },
  {
    id: 'a11',
    userId: 'u11',
    user: {
      id: 'u11',
      fullName: 'Alex',
      avatarColor: 'bg-pink-600',
      initials: 'AL',
      department: 'Toronto Office',
      position: 'Accountant'
    },
    attendanceDate: '2025-11-19',
    status: 'Working',
    firstClockInAt: '2025-11-19T09:00:00',
    finalClockOutAt: '2025-11-19T17:00:00',
    totalWorkingDurationSec: 28800
  },
  {
    id: 'a12',
    userId: 'u12',
    user: {
      id: 'u12',
      fullName: 'Sarah',
      avatarColor: 'bg-purple-600',
      initials: 'SA',
      department: 'Orlando Operation Team',
      position: 'Dispatcher'
    },
    attendanceDate: '2025-11-19',
    status: 'In break',
    firstClockInAt: '2025-11-19T08:30:00',
    finalClockOutAt: '2025-11-19T16:30:00',
    totalWorkingDurationSec: 28800
  }
];
